export { TemplateApp } from './App'
export { templateConfig } from './template.config'
export { APP_ROUTES } from './types'
export type { AppRoute, BadgeTone, CommandItem, DemoRecord, MetricCard, NavItem, ShellSlot, SurfaceCommand, SurfaceDefinition, SurfaceNav, SurfaceRegistry, TemplateBrand, TemplateConfig, Tone, WebsiteContent, WebsiteFaq, WebsiteFeature } from './types'
export { defineSurfaceRegistry, isAppRoute, isRouteEnabled, selectCommandItems, selectEnabledRoutes, selectNavItems } from './surface-registry'
export { CommandPalette, matchesCommand } from './components/command/CommandPalette'
export type { CommandPaletteProps } from './components/command/CommandPalette'
export { AppShell } from './components/shell/AppShell'
export type { AppShellChrome, AppShellProps } from './components/shell/AppShell'
export { ThemeProvider, useTheme } from './theme'
export type { Theme, ThemeContextValue, ThemeProviderProps } from './components/providers/ThemeProvider'
export { ToastProvider, useToast } from './components/providers/ToastProvider'
export type { Toast, ToastContextValue, ToastInput, ToastProviderProps } from './components/providers/ToastProvider'
export { TemplateProviders } from './components/providers/TemplateProviders'
export type { TemplateProvidersProps } from './components/providers/TemplateProviders'
export { Badge, Card, Dialog, EmptyState, ErrorState, Facet, LoadingState, MetricTile, PageHeader, StatusDot, Summary, Tooltip } from './components/ui'
export type { BadgeProps, StatusDotProps } from './components/ui/Badge'
export type { CardProps, FacetProps, MetricTileProps, SummaryItem, SummaryProps } from './components/ui/Card'
export type { DialogProps } from './components/ui/Dialog'
export type { PageHeaderProps } from './components/ui/PageHeader'
export type { EmptyStateProps, ErrorStateProps, LoadingStateProps } from './components/ui/StateBlocks'
export type { TooltipProps } from './components/ui/Tooltip'
